### ISSUE TITLE
Refactor 01

### ISSUE THREAD

**Issue by amcooper** [amcooper/choperator#2]
Attn: @jkonowitch 
Reflected here is a mostly successful refactor of the code in accordance with our discussions of 20150805 Wed.
- The `forEach` loop over the regex matcher array was behaving asynchronously, so I used a `for` loop.
- I included a URL link generation library, Autolinker. Haven't yet had time to tweak this to display images, but I will.

**Comment by jkonowitch** [comment]
Looks good!

For each should have worked though...we can look at that.

And you've got some whitespace issues - you want tab size 2 but your editor may not be setup that way so it looks a bit jenky. I can help you with that.
